AllCops:
  Exclude:
    - 'bin/*'
    - 'config.ru'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'spec/*_helper.rb'
    - 'Rakefile'
  NewCops: enable

Metrics/BlockLength:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal
